// One trailing semicolon per statement, preceded by no whitespace.
const TRAILING_SEMI_OR_SPACE = /[\s;]+$/;

/**
 * Split a migration's SQL script into individual statement strings, ensuring
 * each is terminated by exactly one semicolon. Empty or whitespace-only lines
 * between statements are discarded; nothing else is reformatted.
 */
export function normalizeSqlStatements(sql: string): string[] {
    return sql
        .split(/;\s*\n/)
        .map(stmt => stmt.replace(TRAILING_SEMI_OR_SPACE, "").trim())
        .filter(stmt => stmt.length > 0)
        .map(stmt => stmt + ";");
}

/** Turn a migration id+name into the target `.sql` filename (Wrangler-compatible). */
export function d1MigrationFilename(input: { id: string; name: string }): string {
    return input.id + "_" + input.name + ".sql";
}

/** Assemble the final file contents (header + statements + trailing newline). */
export function buildSqlFileContents(input: {
    sourceFilename: string;
    statements: string[];
}): string {
    let header = [
        "-- Generated by db/generate-d1-migrations.ts from db/migrations/" +
            input.sourceFilename +
            ".",
        "-- Do not edit by hand. Re-run `vp db:migrations:generate` to update.",
        "",
    ];
    return [...header, ...input.statements, ""].join("\n");
}
