import type { SqlStatement } from "remix/data-table";

// One trailing semicolon per statement, preceded by no whitespace.
const TRAILING_SEMI_OR_SPACE = /[\s;]+$/;

/**
 * Normalize compiled `SqlStatement[]` into ready-to-write SQL text lines.
 *
 * The data-table compiler emits parameterized SQL (`text`, `values`), but
 * migration DDL has no bound values. If any do show up — e.g. a migration
 * inserted a literal via `db.insert(...)` — we refuse to emit because the
 * `.sql` file would lose the parameters and execute incorrect SQL.
 */
export function normalizeSqlStatements(statements: SqlStatement[]): string[] {
    return statements.map(stmt => {
        if (stmt.values.length > 0) {
            throw new Error(
                "Cannot emit a migration SQL statement with bound values: " +
                    JSON.stringify(stmt.values) +
                    ". Migrations must use only schema operations when generating D1 SQL.",
            );
        }
        let trimmed = stmt.text.replace(TRAILING_SEMI_OR_SPACE, "");
        if (trimmed.length === 0) {
            throw new Error("Refusing to emit empty SQL statement");
        }
        return trimmed + ";";
    });
}

/** Turn a migration id+name into the target `.sql` filename (Wrangler-compatible). */
export function d1MigrationFilename(input: { id: string; name: string }): string {
    return input.id + "_" + input.name + ".sql";
}

/** Assemble the final file contents (header + statements + trailing newline). */
export function buildSqlFileContents(input: {
    sourceFilename: string;
    statements: string[];
}): string {
    let header = [
        "-- Generated by db/generate-d1-migrations.ts from db/migrations/" +
            input.sourceFilename +
            ".",
        "-- Do not edit by hand. Re-run `vp db:migrations:generate` to update.",
        "",
    ];
    return [...header, ...input.statements, ""].join("\n");
}
