[plugins]
vite-plus = "https://github.com/markmals/mise-vite-plus"

[tools]
bun = "latest"
vite-plus = "latest"

[env]
_.path = [
    # Redirect Node executables to use Bun instead
    '{{config_root}}/.mise/shims',
    '{{config_root}}/node_modules/.bin',
]

[hooks]
postinstall = """
if [ "$CI" = "true" ]; then
  exit 0
fi

# Fix errors when trying to use Vite/Vite+ dev server in Bun
cd node_modules
rm -rf vite
ln -s @voidzero-dev/vite-plus-core vite

bun install
"""

[tasks.dev]
description = "Run the development server"
run = "bunx --bun vp dev --host"

[tasks.build]
description = "Build the app"
sources = [
    "pnpm-lock.yaml",
    "pnpm-workspace.yaml",
    "vite.config.ts",
    "tsconfig.json",
    "app/**/*.{ts,tsx,css}",
]
outputs = ["build"]
run = "bunx --bun vp build"

[tasks.preview]
description = "Preview the built application"
depends = "build"
run = "bunx --bun vp preview"

[tasks.serve]
description = "Serve the production application"
depends = "build"
run = "bun run server.ts"

[tasks.fmt]
description = "Format the entire project"
run = "vp fmt"

[tasks.lint]
description = "Lint the entire project"
run = "vp lint"

[tasks.check]
description = "Format, lint, and typecheck the entire project"
run = "vp check --fix"

[tasks.typecheck]
description = "Typecheck the entire project"
run = "tsgo --noEmit"
