onlyBuiltDependencies:
  - '@remix-run/async-context-middleware'
  - '@remix-run/component'
  - '@remix-run/compression-middleware'
  - '@remix-run/cookie'
  - '@remix-run/data-schema'
  - '@remix-run/fetch-proxy'
  - '@remix-run/fetch-router'
  - '@remix-run/file-storage'
  - '@remix-run/form-data-middleware'
  - '@remix-run/form-data-parser'
  - '@remix-run/fs'
  - '@remix-run/headers'
  - '@remix-run/html-template'
  - '@remix-run/interaction'
  - '@remix-run/lazy-file'
  - '@remix-run/logger-middleware'
  - '@remix-run/method-override-middleware'
  - '@remix-run/mime'
  - '@remix-run/multipart-parser'
  - '@remix-run/node-fetch-server'
  - '@remix-run/response'
  - '@remix-run/route-pattern'
  - '@remix-run/session'
  - '@remix-run/session-middleware'
  - '@remix-run/static-middleware'
  - '@remix-run/tar-parser'
  - esbuild
  - remix
